server:
  port: 8085

spring:
  application:
    name: ms-spring-webflux-sql
  r2dbc:
    url: r2dbc:postgresql://ep-dawn-tree-a4ljgh25-pooler.us-east-1.aws.neon.tech/angelina_napaico_26?sslmode=require
    username: neondb_owner
    password: npg_nWMr07oxSeBA
  sql:
    init:
      mode: never
      schema-locations: classpath:schema.sql

springdoc:
  api-docs:
    enable: true
    path: /api-docs
  swagger-ui:
    enable: true
    path: /swagger-ui.html